/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author ASUS
 */
public class Frame_Terapi_Kimia extends javax.swing.JFrame {

    /**
     * Creates new form Frame_Terapi_Kimia
     */
    public Frame_Terapi_Kimia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        k_terapi = new javax.swing.JTextField();
        n_terapi = new javax.swing.JTextField();
        d_terapi = new javax.swing.JTextField();
        k_dokter = new javax.swing.JTextField();
        biaya_terapi = new javax.swing.JComboBox<>();
        k_pasien = new javax.swing.JTextField();
        b_home = new javax.swing.JButton();
        b_submit = new javax.swing.JButton();
        b_delete = new javax.swing.JButton();
        b_next = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Kode Terapi");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 64, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nama Terapi");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 119, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Deskripsi");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 172, 66, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Kode Dokter");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 275, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Kode Pasien");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 315, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Biaya Terapi");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 395, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Terapi Kimia");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 0, -1, -1));
        getContentPane().add(k_terapi, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 62, 532, -1));
        getContentPane().add(n_terapi, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 117, 532, -1));
        getContentPane().add(d_terapi, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 172, 532, 83));
        getContentPane().add(k_dokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 273, 532, -1));

        biaya_terapi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        biaya_terapi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "150.000", "300.000", "500.000", "1.000.000", "1.500.000", "2.000.000" }));
        getContentPane().add(biaya_terapi, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 392, 183, -1));
        getContentPane().add(k_pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 313, 532, -1));

        b_home.setBackground(new java.awt.Color(153, 153, 0));
        b_home.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        b_home.setText("Home");
        getContentPane().add(b_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 7, 85, -1));

        b_submit.setBackground(new java.awt.Color(102, 255, 255));
        b_submit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        b_submit.setText("Sumbit");
        getContentPane().add(b_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 110, -1));

        b_delete.setBackground(new java.awt.Color(255, 102, 102));
        b_delete.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        b_delete.setText("Delete");
        getContentPane().add(b_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 450, 108, -1));

        b_next.setBackground(new java.awt.Color(51, 255, 255));
        b_next.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        b_next.setText("Next");
        b_next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_nextMouseClicked(evt);
            }
        });
        getContentPane().add(b_next, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 91, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\Tubes_PBO\\Tubes_PBO_Kelompok9\\src\\GUI\\Backgorund\\back_1.jpg")); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 900, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_nextMouseClicked
        // TODO add your handling code here:
        Frame_Payment jF = new Frame_Payment();
        jF.setVisible(true);
    }//GEN-LAST:event_b_nextMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Terapi_Kimia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Terapi_Kimia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Terapi_Kimia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Terapi_Kimia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Terapi_Kimia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_delete;
    private javax.swing.JButton b_home;
    private javax.swing.JButton b_next;
    private javax.swing.JButton b_submit;
    private javax.swing.JComboBox<String> biaya_terapi;
    private javax.swing.JTextField d_terapi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField k_dokter;
    private javax.swing.JTextField k_pasien;
    private javax.swing.JTextField k_terapi;
    private javax.swing.JTextField n_terapi;
    // End of variables declaration//GEN-END:variables
}
