/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Update;
import GUI.Data.*;

/**
 *
 * @author ASUS
 */
public class Frame_HomeAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Frame_Home
     */
    public Frame_HomeAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_dokter = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btn_pasien = new javax.swing.JButton();
        btn_administrator = new javax.swing.JButton();
        btn_farmasi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_payment = new javax.swing.JButton();
        btn_rekamMedik = new javax.swing.JButton();
        btn_terapi = new javax.swing.JButton();
        btn_terapiKimia = new javax.swing.JButton();
        btn_Psikologis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_dokter.setBackground(new java.awt.Color(51, 255, 255));
        btn_dokter.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_dokter.setText("Dokter");
        btn_dokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dokterMouseClicked(evt);
            }
        });
        btn_dokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dokterActionPerformed(evt);
            }
        });
        getContentPane().add(btn_dokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 111, -1));

        jPanel1.setBackground(new java.awt.Color(37, 41, 88));

        btn_pasien.setBackground(new java.awt.Color(255, 0, 255));
        btn_pasien.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_pasien.setText("Pasien");
        btn_pasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pasienMouseClicked(evt);
            }
        });
        btn_pasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pasienActionPerformed(evt);
            }
        });

        btn_administrator.setBackground(new java.awt.Color(204, 204, 0));
        btn_administrator.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_administrator.setText("Administrator");
        btn_administrator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_administratorMouseClicked(evt);
            }
        });
        btn_administrator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_administratorActionPerformed(evt);
            }
        });

        btn_farmasi.setBackground(new java.awt.Color(255, 204, 102));
        btn_farmasi.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_farmasi.setText("Farmasi");
        btn_farmasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_farmasiMouseClicked(evt);
            }
        });
        btn_farmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_farmasiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data Puskesmas");

        btn_payment.setBackground(new java.awt.Color(255, 204, 102));
        btn_payment.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_payment.setText("Payment");
        btn_payment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_paymentMouseClicked(evt);
            }
        });
        btn_payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_paymentActionPerformed(evt);
            }
        });

        btn_rekamMedik.setBackground(new java.awt.Color(255, 204, 102));
        btn_rekamMedik.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_rekamMedik.setText("Rekam Medik");
        btn_rekamMedik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_rekamMedikMouseClicked(evt);
            }
        });
        btn_rekamMedik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rekamMedikActionPerformed(evt);
            }
        });

        btn_terapi.setBackground(new java.awt.Color(255, 204, 102));
        btn_terapi.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_terapi.setText("Terapi");
        btn_terapi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_terapiMouseClicked(evt);
            }
        });
        btn_terapi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_terapiActionPerformed(evt);
            }
        });

        btn_terapiKimia.setBackground(new java.awt.Color(255, 204, 102));
        btn_terapiKimia.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_terapiKimia.setText("Terapi Kimia");
        btn_terapiKimia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_terapiKimiaMouseClicked(evt);
            }
        });
        btn_terapiKimia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_terapiKimiaActionPerformed(evt);
            }
        });

        btn_Psikologis.setBackground(new java.awt.Color(255, 204, 102));
        btn_Psikologis.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_Psikologis.setText("Terapi Psikologis");
        btn_Psikologis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_PsikologisMouseClicked(evt);
            }
        });
        btn_Psikologis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PsikologisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Psikologis, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_terapiKimia, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_terapi, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_rekamMedik, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_payment, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_farmasi, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_pasien)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_administrator)
                                .addGap(116, 116, 116)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(104, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(btn_pasien)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btn_administrator))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addComponent(btn_farmasi)
                .addGap(31, 31, 31)
                .addComponent(btn_payment)
                .addGap(32, 32, 32)
                .addComponent(btn_rekamMedik)
                .addGap(34, 34, 34)
                .addComponent(btn_terapi)
                .addGap(43, 43, 43)
                .addComponent(btn_terapiKimia)
                .addGap(27, 27, 27)
                .addComponent(btn_Psikologis)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dokterActionPerformed

    private void btn_pasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pasienMouseClicked
        // TODO add your handling code here:
        Frame_DataPasien jF = new Frame_DataPasien();
        jF.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_pasienMouseClicked

    private void btn_farmasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_farmasiMouseClicked
        // TODO add your handling code here:
        Frame_DataFarmasi jF = new Frame_DataFarmasi();
        jF.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_farmasiMouseClicked

    private void btn_administratorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_administratorMouseClicked
        // TODO add your handling code here:
        Frame_DataAdministrator jF_1 = new Frame_DataAdministrator();
        jF_1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_administratorMouseClicked

    private void btn_dokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dokterMouseClicked
        // TODO add your handling code here:
        Frame_DataDokter jF_1 = new Frame_DataDokter();
        jF_1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_dokterMouseClicked

    private void btn_pasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pasienActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_pasienActionPerformed

    private void btn_farmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_farmasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_farmasiActionPerformed

    private void btn_administratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_administratorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_administratorActionPerformed

    private void btn_paymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_paymentMouseClicked
        // TODO add your handling code here:
        Frame_DataPayment jF_1 = new Frame_DataPayment();
        jF_1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_paymentMouseClicked

    private void btn_paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_paymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_paymentActionPerformed

    private void btn_rekamMedikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_rekamMedikMouseClicked
        // TODO add your handling code here:
        Frame_DataRekamMedik jF_1 = new Frame_DataRekamMedik();
        jF_1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_rekamMedikMouseClicked

    private void btn_rekamMedikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rekamMedikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_rekamMedikActionPerformed

    private void btn_terapiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_terapiMouseClicked
        // TODO add your handling code here:
        Frame_DataTerapi jF_1 = new Frame_DataTerapi();
        jF_1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_terapiMouseClicked

    private void btn_terapiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_terapiActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_terapiActionPerformed

    private void btn_terapiKimiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_terapiKimiaMouseClicked
        // TODO add your handling code here:
        Frame_DataTerapiKimia jF_1 = new Frame_DataTerapiKimia();
        jF_1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_terapiKimiaMouseClicked

    private void btn_terapiKimiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_terapiKimiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_terapiKimiaActionPerformed

    private void btn_PsikologisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PsikologisMouseClicked
        // TODO add your handling code here:
        Frame_DataTerapiPsikologis jF_1 = new Frame_DataTerapiPsikologis();
        jF_1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_PsikologisMouseClicked

    private void btn_PsikologisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PsikologisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_PsikologisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_HomeAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Psikologis;
    private javax.swing.JButton btn_administrator;
    private javax.swing.JButton btn_dokter;
    private javax.swing.JButton btn_farmasi;
    private javax.swing.JButton btn_pasien;
    private javax.swing.JButton btn_payment;
    private javax.swing.JButton btn_rekamMedik;
    private javax.swing.JButton btn_terapi;
    private javax.swing.JButton btn_terapiKimia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
