/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Update;

import Database.DB_Terapi_Psikologis;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Frame_TerapiPsikologis extends javax.swing.JFrame {

    /**
     * Creates new form Frame_Terapi_Psikologis
     */
    public Frame_TerapiPsikologis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1_Back = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton1_reset = new javax.swing.JButton();
        jTextField4_BiayaTerapi = new javax.swing.JTextField();
        jButton2_Delete = new javax.swing.JButton();
        jButton4_Add = new javax.swing.JButton();
        jButton3_Update = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField4_KodeDokter = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3_Deskripsi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2_NamaTerapi = new javax.swing.JTextField();
        jTextField1_KodeTerapi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Terapi Psikologis");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 220, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kode Terapi     :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Terapi    :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jButton1_Back.setBackground(new java.awt.Color(153, 153, 0));
        jButton1_Back.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1_Back.setText("Back");
        jButton1_Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1_BackMouseClicked(evt);
            }
        });
        getContentPane().add(jButton1_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 104, -1));

        jPanel1.setBackground(new java.awt.Color(37, 41, 88));

        jButton1_reset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1_reset.setText("reset");
        jButton1_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1_resetMouseClicked(evt);
            }
        });

        jButton2_Delete.setBackground(new java.awt.Color(255, 51, 51));
        jButton2_Delete.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2_Delete.setText("Delete");
        jButton2_Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2_DeleteMouseClicked(evt);
            }
        });

        jButton4_Add.setBackground(new java.awt.Color(51, 255, 255));
        jButton4_Add.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton4_Add.setText("add");
        jButton4_Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4_AddMouseClicked(evt);
            }
        });

        jButton3_Update.setBackground(new java.awt.Color(51, 255, 255));
        jButton3_Update.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3_Update.setText("update");
        jButton3_Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3_UpdateMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Biaya Terapi    :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kode Dokter   :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Deskripsi          :");

        jTextField1_KodeTerapi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_KodeTerapiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(369, 369, 369)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1_KodeTerapi, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2_NamaTerapi, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3_Deskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4_KodeDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4_BiayaTerapi, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jButton1_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jButton2_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jButton3_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(jTextField1_KodeTerapi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jTextField2_NamaTerapi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField3_Deskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4_KodeDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4_BiayaTerapi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4_Add)
                            .addComponent(jButton1_reset)
                            .addComponent(jButton2_Delete)
                            .addComponent(jButton3_Update)))
                    .addComponent(jLabel4))
                .addGap(39, 39, 39))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3_UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3_UpdateMouseClicked
        // TODO add your handling code here:
        DB_Terapi_Psikologis farmasi = new DB_Terapi_Psikologis(
                jTextField1_KodeTerapi.getText(), 
                jTextField2_NamaTerapi.getText(), 
                jTextField3_Deskripsi.getText(), 
                jTextField4_KodeDokter.getText(), 
                Integer.parseInt(jTextField4_BiayaTerapi.getText())
        );
        farmasi.update();
        JOptionPane.showMessageDialog(null, "Data Berhasil Diupdate..");
    }//GEN-LAST:event_jButton3_UpdateMouseClicked

    private void jTextField1_KodeTerapiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_KodeTerapiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_KodeTerapiActionPerformed

    private void jButton1_BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_BackMouseClicked
        // TODO add your handling code here:
        Frame_Home jF = new Frame_Home();
        jF.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1_BackMouseClicked

    private void jButton4_AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4_AddMouseClicked
        // TODO add your handling code here:
        DB_Terapi_Psikologis farmasi = new DB_Terapi_Psikologis(
                jTextField1_KodeTerapi.getText(), 
                jTextField2_NamaTerapi.getText(), 
                jTextField3_Deskripsi.getText(), 
                jTextField4_KodeDokter.getText(), 
                Integer.parseInt(jTextField4_BiayaTerapi.getText())
        );
        farmasi.insert();
        JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan..");
    }//GEN-LAST:event_jButton4_AddMouseClicked

    private void jButton2_DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2_DeleteMouseClicked
        // TODO add your handling code here:
        DB_Terapi_Psikologis farmasi = new DB_Terapi_Psikologis(
                jTextField1_KodeTerapi.getText(), 
                jTextField2_NamaTerapi.getText(), 
                jTextField3_Deskripsi.getText(), 
                jTextField4_KodeDokter.getText(), 
                Integer.parseInt(jTextField4_BiayaTerapi.getText())
        );
        farmasi.delete();
        JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus..");
    }//GEN-LAST:event_jButton2_DeleteMouseClicked

    private void jButton1_resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_resetMouseClicked
        // TODO add your handling code here:
        DB_Terapi_Psikologis farmasi = new DB_Terapi_Psikologis(
                jTextField1_KodeTerapi.getText(), 
                jTextField2_NamaTerapi.getText(), 
                jTextField3_Deskripsi.getText(), 
                jTextField4_KodeDokter.getText(), 
                Integer.parseInt(jTextField4_BiayaTerapi.getText())
        );
        farmasi.reset();
        JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus..");
    }//GEN-LAST:event_jButton1_resetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_TerapiPsikologis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_TerapiPsikologis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_TerapiPsikologis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_TerapiPsikologis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_TerapiPsikologis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Back;
    private javax.swing.JButton jButton1_reset;
    private javax.swing.JButton jButton2_Delete;
    private javax.swing.JButton jButton3_Update;
    private javax.swing.JButton jButton4_Add;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1_KodeTerapi;
    private javax.swing.JTextField jTextField2_NamaTerapi;
    private javax.swing.JTextField jTextField3_Deskripsi;
    private javax.swing.JTextField jTextField4_BiayaTerapi;
    private javax.swing.JTextField jTextField4_KodeDokter;
    // End of variables declaration//GEN-END:variables
}
