/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Update;

/**
 *
 * @author ASUS
 */
public class Frame_TerapiKimia extends javax.swing.JFrame {

    /**
     * Creates new form Frame_Terapi_Kimia
     */
    public Frame_TerapiKimia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        kode_terapi = new javax.swing.JTextField();
        nama_terapi = new javax.swing.JTextField();
        deskripsi_terapi = new javax.swing.JTextField();
        kode_dokter = new javax.swing.JTextField();
        biaya_terapi = new javax.swing.JComboBox<>();
        kode_pasien = new javax.swing.JTextField();
        b_home = new javax.swing.JButton();
        b_add = new javax.swing.JButton();
        b_update = new javax.swing.JButton();
        b_delete = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Kode Terapi");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama Terapi");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Deskripsi");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 66, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kode Dokter");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kode Pasien");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Biaya Terapi");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Terapi Kimia");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));
        getContentPane().add(kode_terapi, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 532, -1));
        getContentPane().add(nama_terapi, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 532, -1));
        getContentPane().add(deskripsi_terapi, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 532, 83));
        getContentPane().add(kode_dokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 532, -1));

        biaya_terapi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        biaya_terapi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "150.000", "300.000", "500.000", "1.000.000", "1.500.000", "2.000.000" }));
        getContentPane().add(biaya_terapi, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 183, -1));
        getContentPane().add(kode_pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 532, -1));

        b_home.setBackground(new java.awt.Color(153, 153, 0));
        b_home.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        b_home.setText("Back");
        getContentPane().add(b_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 85, -1));

        b_add.setBackground(new java.awt.Color(102, 255, 255));
        b_add.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        b_add.setText("add");
        getContentPane().add(b_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 110, -1));

        b_update.setBackground(new java.awt.Color(255, 102, 102));
        b_update.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        b_update.setText("update");
        b_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_updateActionPerformed(evt);
            }
        });
        getContentPane().add(b_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, 108, -1));

        b_delete.setBackground(new java.awt.Color(51, 255, 255));
        b_delete.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        b_delete.setText("delete");
        b_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_deleteMouseClicked(evt);
            }
        });
        getContentPane().add(b_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 520, 91, -1));

        jPanel1.setBackground(new java.awt.Color(37, 41, 88));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_deleteMouseClicked
        // TODO add your handling code here:
        Frame_Payment jF = new Frame_Payment();
        jF.setVisible(true);
    }//GEN-LAST:event_b_deleteMouseClicked

    private void b_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_updateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_TerapiKimia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_TerapiKimia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_TerapiKimia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_TerapiKimia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_TerapiKimia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_add;
    private javax.swing.JButton b_delete;
    private javax.swing.JButton b_home;
    private javax.swing.JButton b_update;
    private javax.swing.JComboBox<String> biaya_terapi;
    private javax.swing.JTextField deskripsi_terapi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField kode_dokter;
    private javax.swing.JTextField kode_pasien;
    private javax.swing.JTextField kode_terapi;
    private javax.swing.JTextField nama_terapi;
    // End of variables declaration//GEN-END:variables
}
