/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Update;

import Class.Administrator;
import Database.DB_Administrator;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Frame_Login extends javax.swing.JFrame {
    public static boolean status_admin = false;
    
    /**
     * Creates new form Frame_Login
     */
    public boolean get_status(){
        return status_admin;
    }
    
    public Frame_Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1_Submit = new javax.swing.JButton();
        jButton2_Home = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2_Password = new javax.swing.JTextField();
        jTextField1_Username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(37, 41, 88));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1_Submit.setBackground(new java.awt.Color(0, 255, 255));
        jButton1_Submit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1_Submit.setText("Login");
        jButton1_Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1_SubmitMouseClicked(evt);
            }
        });
        jPanel1.add(jButton1_Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, 92, -1));

        jButton2_Home.setBackground(new java.awt.Color(204, 204, 0));
        jButton2_Home.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2_Home.setText("Home");
        jButton2_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2_HomeMouseClicked(evt);
            }
        });
        jPanel1.add(jButton2_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, 94, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));
        jPanel1.add(jTextField2_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 450, -1));
        jPanel1.add(jTextField1_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 450, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sign-in Administrator");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_SubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_SubmitMouseClicked
        // TODO add your handling code here:
        String username = jTextField1_Username.getText();
        String password = jTextField2_Password.getText();
        DB_Administrator DB_admin = new DB_Administrator(null, null);
        ArrayList<Administrator> admin = DB_admin.getData();
        for (Administrator e: admin){
            if (username.equals(e.getUsername()) && password.equals(e.getPassword())){
                status_admin = true;
                Frame_HomeAdmin jF = new Frame_HomeAdmin();
                jF.setVisible(true);
                setVisible(false);
                JOptionPane.showMessageDialog(null, "Login Berhasil..");
                break;
            }
        }
        if (status_admin==false){
            JOptionPane.showMessageDialog(null, "Username atau Password Salah..");
        }
        

    }//GEN-LAST:event_jButton1_SubmitMouseClicked

    private void jButton2_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2_HomeMouseClicked
        // TODO add your handling code here:
        Frame_Home jF = new Frame_Home();
        jF.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2_HomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Submit;
    private javax.swing.JButton jButton2_Home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1_Username;
    private javax.swing.JTextField jTextField2_Password;
    // End of variables declaration//GEN-END:variables
}
